# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main, dev, develop, feature/**, fix/** ]
  pull_request:
    branches: [ master, main, dev, develop, feature/**, fix/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run linters':' detekt, ktlint
      run: ./gradlew detekt && ./gradlew ktlintCheck 
    
      
