# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  push:
    branches: [ release, main, develop, feature/**, fix/** ]
  pull_request:
    branches: [ release, main, develop, feature/**, fix/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: { java-version: 1.8 }
      
    - name: "Make gradlew executable"
      run: chmod +x ./gradlew

    - name: Generate cache key
      run: ./checksum.sh checksum.txt

    - uses: actions/cache@v2
      continue-on-error: true # continue if the cache restore/upload fails
      with:
        path: |
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/build-cache-*
        key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

    - name: "Run linters: detekt, ktlint"
      run: ./gradlew detekt && ./gradlew ktlintCheck
    
      
