name: Build release artifacts

on:
  push:
    branches: [ main, main-** ]

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: "Make gradlew executable"
        run: chmod +x ./gradlew

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v2
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: Prepare Secret Files
        run: |
              echo "${{ secrets.KEYSTORE }}" > practicalapp.jks.asc
              gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch practicalapp.jks.asc > practicalapp.jks
              echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties.asc
              gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.properties.asc > keystore.properties

      - name: Build release APK and AAB
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/*release.apk

      - name: Upload Aab
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/*release.aab
